create table ods(
  id                                  DECIMAL(20, 0),
  company_id                          DECIMAL(20, 0),
  company_type                        TINYINT,
  company_name                        STRING,
  company_name_english                STRING,
  establish_date                      TIMESTAMP(3),
  register_addr                       STRING,
  register_capital_amt                DECIMAL(20, 0),
  register_capital_currency           INT,
  actual_capital_amt                  DECIMAL(20, 0),
  actual_capital_currency             INT,
  company_registation_status          STRING,
  company_logo_url                    STRING,
  company_shortname                   STRING,
  company_phone                       STRING,
  company_email                       STRING,
  company_website                     STRING,
  social_security_headcount           BIGINT,
  business_type_id                    DECIMAL(20, 0),
  original_type                       STRING,
  tyc_credit_rating                   INT,
  longitude_by_baidu_api              DECIMAL(20,15),
  latitude_by_baidu_api               DECIMAL(20,15),
  unified_social_credit_code          STRING,
  org_type                            STRING,
  is_micro_enterprise                 TINYINT,
  industry_national_std_lv1_code      STRING,
  industry_national_std_lv2_code      STRING,
  industry_national_std_lv3_code      STRING,
  business_areacode_00                STRING,
  business_areacode_01                STRING,
  business_areacode_02                STRING,
  crawl_time                          TIMESTAMP(3),
  province_base_by_register_institute STRING,
  create_time                         TIMESTAMP(3),
  update_time                         TIMESTAMP(3),
  op_ts                               TIMESTAMP(3),
  PRIMARY KEY (id) NOT ENFORCED
) WITH (
  'connector' = 'hudi',
  'path' = 'obs://hadoop-obs/hudi_ods/company_index',
  'table.type' = 'MERGE_ON_READ',
  -- cdc
  'changelog.enabled' = 'true',
  -- read
  'read.tasks' = '1',
  'read.streaming.enabled' = 'true',
  'read.start-commit' = '20231128000000',
  'read.streaming.check-interval' = '5'
);