dbConfigs:
  # 测试环境
  s9: { host: "ats-staging.mysql.rds.aliyuncs.com",database: "ats_staging_9",user: "moka_root",password: "Moka2015" }
  test: { host: "atsmysql-staging.mokahr.com",database: "test",user: "moka_root",password: "Moka2015",port: 3307 }
  hcmtest: { host: "moka-dev.mysql.rds.aliyuncs.com",database: "moka_hcm_test",user: "hcm",password: "62Kc44!u&8h^jP&V" }
  bitest: { host: "172.28.84.230",database: "bi_test",user: "bi_root",password: "moka_2015" }
  abs1: { host: "rm-2zerod609j61r17h2.mysql.rds.aliyuncs.com",database: "bi_test_abs1",user: "dble_1",password: "moka_123" }
  doristest: { host: "172.28.0.80",port: 9030,database: "bi_test",user: "root",password: "",dorisFeHttpPort: 8040 }
  # 阿里云 生产环境
  mokaproduction: { host: "172.17.96.180",database: "moka_production",user: "apps_read",password: "XMvoh^5xW8W_*Tsc" }
  biproduction: { host: "172.17.47.30",database: "bi_production",user: "bi_apps",password: "ehOdz+PgOmfH1(Z)" }
  abs2: { host: "rm-2zeb366r2pt601k6i.mysql.rds.aliyuncs.com",database: "moka_hcm_production",user: "bi_root",password: ")mZt4+j!3+9cP+d^" }
  dorisproduction: { host: "172.17.47.41",port: 9030,database: "bi_production",user: "root",password: "moka1234" }
  dorisproduction2: { host: "172.17.61.109",port: 9030,database: "bi_production",user: "root",password: "moka1234" }
  hcmproduction: { host: "rm-2ze6f8g69n4hyp5ir.mysql.rds.aliyuncs.com",database: "moka_hcm",user: "olap_read",password: "TI0I5W@o2RKvj@4A" }
  salary: { host: "aly-prod-people-salary.mysql.rds.aliyuncs.com",database: "moka_hcm_salary",user: "user_bi_read",password: "w922X3Htgr6VBlr" }
  backstage: { host: "rm-2zebe3h32729td79u.mysql.rds.aliyuncs.com",database: "backstage",user: "backstage_apps",password: "p$!q+B0TE0" }
  # 腾讯云 生产环境
  txmokaproduction: { host: "tc-prod-ats-dble-slave-mysql.mokahr.com",database: "moka_production",user: "apps_read",password: "XMvoh^5xW8W_*Tsc" }
  txbiproduction: { host: "tc-prod-bi-dble-mysql.mokahr.com",database: "bi_production",user: "bi_apps",password: "ehOdz+PgOmfH1(Z)" }
  txdorisproduction: { host: "tc-prod-bi-node1-doris.mokahr.com",port: 9030,database: "bi_production",user: "root",password: "moka1234" }
  txbackstage: { host: "tc-prod-bi-data-mysql.mokahr.com",database: "backstage",user: "user_bi_readwrite",password: "CtG13z1rtg1d3tY" }

redisConfigs:
  # 测试环境
  redistest: { host: "172.17.89.74",password: "moka1234" }
  redistestnew: { host: "r-2zek4eum7xbg7y44ue.redis.rds.aliyuncs.com",password: "bi_user:0hdPer5rIfXVrDz" }
  # 阿里云 生产环境
  redisprod: { host: "r-2zeu1u0o4nircnvgwd.redis.rds.aliyuncs.com",password: "Moka_bi@2020" }
  # 腾讯云 生产环境
  redistx: { host: "tc-prod-bi-mokabi-redis.mokahr.com",password: "user_moka_bi@04Av7ypdBeCStg" }