flinkSource: Repair # Repair or Kafka

# scanMode: Direct or TumblingWindow
repairTasks:
  - checkpointUid: ""
    sourceName: ""
    tableName: ""
    columns: "*"
    where: "1=1"
    scanMode: Direct

dbConfigs:
  localhost: { host: "127.0.0.1",database: "test",user: "root",password: "Moka20190520" }

redisConfigs:
  localhost: { host: "127.0.0.1",password: ~ }

kafkaConfigs:
  kafkaSource:
    bootstrapServers: ""
    topics:
      - ""
      - ""
      - ""
    groupId: ""
    startFrom: "1"

hbaseDbConfigs:
  hbaseSink:
    zookeeperQuorum: ""

# 库、表、列族信息
hbaseSchemas:
  schema1:
    namespace: ""
    tableName: ""
    columnFamily: ""